### ISSUE TITLE
How to use Proj4 and Transform?

### ISSUE THREAD

**Issue by pmeems** [quentin-ol/ngx-openlayers#118]
After installing this component I am accessing the ol object directly. This is working great. I can now use layer groups as well (see my other question).
I now need to transform a point from epsg:3857 to my custom projection. Using ol.proj.transform it's not working. I can transform a point from 3857 to 4326. I'm assuming I need to create a proper proj.projection but I'm struggling with this part.
Does the component also install proj4.js?
If not wat is the best way to add it? I tried installing npm proj4. That gave me the proj4.js but I can't get it to work either.
If it is already in the component how should I use it?

**Comment by quentin-ol** [comment]
Good questions!
So first, the ones that I can help you with.
- `ngx-openlayers` doesn't pull **proj4.js** as a dependency. It depends on openlayers, its typings and  @angular/animations (I forgot why. Might be interesting to remember!).
- `ngx-openlayers` `coordinates` components accepts any system of reference that Openlayers knows about and apply the appropriate projection to the system of reference of the map. So it might be interesting to check if your projection isn't already supported. 
One idea/question: is it feasible to handle the projection in your controller so that you pass your coordinate in a SR that openlayers knows about ? This is a quick fix and it's not elegant but if you're on a deadline...

**Comment by pmeems** [comment]
Thanks Quentin for your response.

I already add my projection to openlayers using:
```
    this.dutchProjection = new ol.proj.Projection({
      code: 'EPSG:28992',
      // The extent is used to determine zoom level 0. Recommended values for a
      // projection's validity extent can be found at https://epsg.io/.
      extent: [-285401.92, 22598.08, 595402.0, 903402.0],
      worldExtent: [3.2, 50.75, 7.22, 53.7],
      units: 'm'
    });
    ol.proj.addProjection(this.dutchProjection);
```
This works fine and I send the projection code to my backend to get the data in the projection I need.
But when I switch projections I want to change the view center by transforming the current center to the new coordinates.

As mentioned I already installed the proj4 package, but can't get it to work.
I also tried adding 
```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.4.4/proj4.js"/>
  <script src="https://epsg.io/28992.js"></script>
```
to my index.html, but still no luck.

Most likely the problem is with my lack of understanding how to use external js libraries like proj4 in Angular ;)

**Comment by pmeems** [comment]
Answering my own question.

1. Install the proj4 package using npm
2. Add import to your file: import * as proj4x from 'proj4';
3. Define proj4 variable: const proj4 = (proj4x as any).default;
4. Add custom definition:  proj4.defs('EPSG:28992', '+proj=sterea ...); // https://epsg.io/28992.js:
5. Link proj4 to ol in your constructor: ol.proj.setProj4(proj4);
6. Now you can use: ol.proj.get('EPSG:28992')

Hopefully this will help others.

**Comment by chriszrc** [comment]
How did you get a reference to ol in `ol.proj.setProj4(proj4)`, I can't see to get a reference to that root ol object in typescript
