### ISSUE TITLE
ViewChilld bind error

### ISSUE THREAD

**Issue by vinicius8488** [quentin-ol/ngx-openlayers#127]
Hi...
Have the following code:
`  @ViewChild('loteLayer') lote: ol.source.TileWMS;`
and in my component .html:
`     <aol-layer-tile >
                <aol-source-tilewms  #loteLayer [url]`

and in my component .ts have:
`  info(evt: MapBrowserEvent) {`
`var url = this.lote.getGetFeatureInfoUrl()...`
`}`

but when I try to use lote object in my component typescript I get the error:
ERROR TypeError: this.lote.getGetFeatureInfoUrl is not a function

**Comment by quentin-ol** [comment]
Very difficult to help you with such little info. Please provide an example that shows the issue you're describing. Thanks.

**Comment by vinicius8488** [comment]
Sorry... I used ol.source.TileWMS instead of   SourceTileWMSComponent

**Comment by quentinlampin** [comment]
No worries!

-------- Message d'origine --------De : vinicius8488 <notifications@github.com> Date : 16/11/2017  18:55  (GMT+01:00) À : quentin-ol/ngx-openlayers <ngx-openlayers@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : Re: [quentin-ol/ngx-openlayers] ViewChilld bind error (#127) 
Sorry... I used ol.source.TileWMS instead of   SourceTileWMSComponent

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/quentin-ol/ngx-openlayers","title":"quentin-ol/ngx-openlayers","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/quentin-ol/ngx-openlayers"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vinicius8488 in #127: Sorry... I used ol.source.TileWMS instead of   SourceTileWMSComponent"}],"action":{"name":"View Issue","url":"https://github.com/quentin-ol/ngx-openlayers/issues/127#issuecomment-345005147"}}}
