### ISSUE TITLE
feat: Angular 10 Support

### ISSUE THREAD

**Issue by gongAll** [quentin-ol/ngx-openlayers#256]
When I upgrade my project to Angular 10 I get warning messages related to lack of support from ngx-openlayers to angular 10.
Please update ngx-openlayers package to support Angular 10.

**Comment by gongAll** [comment]
So... any news regarding this issue?

**Comment by olierxleben** [comment]
I have created a new Angular application and was able to load the example from readme file. What does not work? Angular 10.1.6

**Comment by ShaiBarak** [comment]
Also happen to me...
There's a lot of messages, for example:
Can't bind to 'ngForOf' since it isn't a known property of 'aol-feature'.
1. If 'aol-source-vector' is an Angular component, then verify that it is part of this module.
2. If 'aol-source-vector' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
1. If 'aol-geometry-point' is an Angular component, then verify that it is part of this module.
2. If 'aol-geometry-point' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by jeremy-eychenne** [comment]
Hi, PR [272](https://github.com/quentin-ol/ngx-openlayers/pull/272) created to adress this issue. Do not hesitate to add feedback in PR if needed.
